# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  telecom_network:

services:
  ca-org1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.telecom.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/44ec6cb058f9afa1a625452d86cba9e1c33d2f2df9bed47a7f7aca49ebaa7d50_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.telecom.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/44ec6cb058f9afa1a625452d86cba9e1c33d2f2df9bed47a7f7aca49ebaa7d50_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.telecom.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_org1_telecom
    networks:
      - telecom_network

  ca-org2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.telecom.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/51dfe9cec48ae6f20d54a1b367e44d08909677ecb892774820e29012ff44f9db_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.telecom.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/51dfe9cec48ae6f20d54a1b367e44d08909677ecb892774820e29012ff44f9db_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.telecom.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_org2_telecom
    networks:
      - telecom_network

  ca-org3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.telecom.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a4f736ae682e4003bdc089225c68405e45c7a54817af2d65cc62c6756a84f4ce_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.telecom.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a4f736ae682e4003bdc089225c68405e45c7a54817af2d65cc62c6756a84f4ce_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.telecom.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_org3_telecom
    networks:
      - telecom_network